meta_product_name: "Comptoir"
meta_title: "Comptoir : rencontrons-nous simplement"
meta_description: "Comptoir redonne du sens à la rencontre en définissant un lieu et une heure de rendez-vous."
meta_image: "cover_social.png" # should exist in `app/assets/images/`
