meta_product_name: "Comptoir"
meta_title: "Comptoir : rencontrons-nous simplement"
meta_description: "Comptoir redonne du sens à la rencontre en définissant un lieu et une heure de rendez-vous."
meta_image: "https://github.com/JulesRn/rails-comptoir/blob/master/app/assets/images/cover_social.png?raw=true" # should exist in `app/assets/images/`
